DROP TABLE CH_USER CASCADE CONSTRAINTS;

CREATE TABLE CH_USER (
       CD_USER			NUMBER(4)		 	NOT NULL,
       LOGIN_USER   	VARCHAR2(50)		NOT NULL,
       PASSWORD_USER	VARCHAR2(100)	 	NOT NULL
);

ALTER TABLE CH_USER
       ADD CONSTRAINT PK_CH_USER PRIMARY KEY (CD_USER);

INSERT INTO CH_USER VALUES (1, 'edneyroldao', 'abc1232');
INSERT INTO CH_USER VALUES (2, 'nadineroldao', 'abc1111');
